[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
coinflip = "8QvsmhwMtFXYZn2LZzaUgSenBuHfoEeAtJcr1qtRr3wj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "../key/G2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
