[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
coinflip = "3bTdj7J5jzTJ1BByYzUkyNFdCUBejB1TcG6UM5czR6up"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=27fd6baa-75e9-4d39-9832-d5a43419ad78"
wallet = "./1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
